import numpy as np
from EMD import emd

__all__ = 'EEMD'

def eemd(data, extrapolation='mirror', nimfs=12, shifting_distance=0.2):
    """
    Perform a Ensemble Empirical Mode Decomposition on a data set.
    
    This function will return an array of all the Imperical Mode Functions as 
    defined in [1]_, which can be used for further Hilbert Spectral Analysis.
    
    The EEMD generates several noised signals generated by adding
    white noise to original signal, performs EMD on each noised signals and
    average the IMFs with the same mode from different noised signals. 
    
    Parameters
    ----------
    data : array_like
            Signal Data
    extrapolation : str, optional
            Sets the extrapolation method for edge effects. 
            Options: None
                     'mirror'
            Default: 'mirror'
    nimfs : int, optional
            Sets the maximum number of IMFs to be found
            Default : 12
    shifiting_distance : float, optional
            Sets the minimum variance between IMF iterations.
            Default : 0.2
    n_noised_data : int, optional
            Sets the number of noised data generated.
            Default : 10
    noise_variance : float, optional
            Sets the variance of white noise added on original signal.
            Default : 1
    Returns
    -------
    IMFs : ndarray
            An array of shape (len(data),N) where N is the number of found IMFs
    
    Notes
    -----
    
    References
    ----------
    .. [1] 
    Zhaohua Wu, Norden E. Huang 2005 'Ensemble empirical mode decomposition:
    A noise assisted data analysis method'
    Advances in Adaptive Data Analysis 01, 1-41
    """

    white_noises = np.random.normal(0.0, noise_variance, 
        (n_noised_data, len(data)))
    noised_datas = data + white_noises
    IMFss = np.apply_along_axis(emd, 1, noised_datas, 
        [extrapolation, nimfs, shifting_distance])
    IMFs = np.mean(IMFss, 0)
    return IMFs
